/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uitrs.game.majiang;

import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.websocket.Session;

import com.uitrs.game.majiang.client.service.CommonSevice;
import com.uitrs.game.majiang.client.service.SuperClientService;

/**
 *
 * @author lucio
 */
public class MainJFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = 6897537677279987868L;
	private WeixinJDialog weixin;

	/**
	 * Creates new form MainJFrame
	 */
	public MainJFrame() {
		Toolkit tk = Toolkit.getDefaultToolkit();
		Dimension screensize = tk.getScreenSize();
		int height = screensize.height;
		int width = screensize.width;
		initComponents();
		weixin = new WeixinJDialog(this, true);
		this.setLocation(width / 2 - this.getWidth() / 2, height / 2 - this.getHeight() / 2);
		SuperClientService.init();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextFieldUri = new javax.swing.JTextField();
		jSeparator1 = new javax.swing.JSeparator();
		jButtonConnect = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jButtonSend = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jEditorPaneSend = new javax.swing.JEditorPane();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jEditorPaneReceive = new javax.swing.JEditorPane();
		jButtonClose = new javax.swing.JButton();
		jButtonLogin = new javax.swing.JButton();
		jButtonCreate = new javax.swing.JButton();
		jButtonJoin = new javax.swing.JButton();
		jButtonReady = new javax.swing.JButton();
		jButtonOutCard = new javax.swing.JButton();
		jButtonFetch = new javax.swing.JButton();
		jButtonPeng = new javax.swing.JButton();
		jButtonAnGang = new javax.swing.JButton();
		jButtonMingGang = new javax.swing.JButton();
		jButtonBuGang = new javax.swing.JButton();
		jButtonHu = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jTextFieldHand = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextFieldOpts = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextFieldHua = new javax.swing.JTextField();
		jComboBoxHand = new javax.swing.JComboBox<String>();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("麻将测试客户端");
		setLocation(new java.awt.Point(400, 200));
		setPreferredSize(new java.awt.Dimension(980, 640));

		jLabel1.setText("WebSocket Uri:");

		jTextFieldUri.setText("ws://192.168.0.114:8080/quanzhou/ws/qzmj");
		jTextFieldUri.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldUriActionPerformed(evt);
			}
		});

		jButtonConnect.setText("Connect");
		jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonConnectActionPerformed(evt);
			}
		});

		jLabel2.setText("Send Message:");

		jButtonSend.setText("发送");
		jButtonSend.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSendActionPerformed(evt);
			}
		});

		jEditorPaneSend.setMinimumSize(new java.awt.Dimension(110, 20));
		jScrollPane1.setViewportView(jEditorPaneSend);

		jLabel3.setText("Receive Message:");

		jEditorPaneReceive.setPreferredSize(new java.awt.Dimension(110, 20));
		jScrollPane2.setViewportView(jEditorPaneReceive);

		jButtonClose.setText("Close");
		jButtonClose.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCloseActionPerformed(evt);
			}
		});

		jButtonLogin.setText("Login");
		jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonLoginActionPerformed(evt);
			}
		});

		jButtonCreate.setText("创建房间");
		jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCreateActionPerformed(evt);
			}
		});

		jButtonJoin.setText("加入房间");
		jButtonJoin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonJoinActionPerformed(evt);
			}
		});

		jButtonReady.setText("准备");
		jButtonReady.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonReadyActionPerformed(evt);
			}
		});

		jButtonOutCard.setText("出牌");
		jButtonOutCard.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonOutCardActionPerformed(evt);
			}
		});

		jButtonFetch.setText("拿牌");
		jButtonFetch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonFetchActionPerformed(evt);
			}
		});

		jButtonPeng.setText("碰");
		jButtonPeng.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonPengActionPerformed(evt);
			}
		});

		jButtonAnGang.setText("暗杠");
		jButtonAnGang.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAnGangActionPerformed(evt);
			}
		});

		jButtonMingGang.setText("明杠");
		jButtonMingGang.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonMingGangActionPerformed(evt);
			}
		});

		jButtonBuGang.setText("补杠");
		jButtonBuGang.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonBuGangActionPerformed(evt);
			}
		});

		jButtonHu.setText("胡牌");
		jButtonHu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonHuActionPerformed(evt);
			}
		});

		jLabel4.setText("手牌:");

		jTextFieldHand.setText("w1,w2,w3,t1,t2,t3,i1,h1,f1,f2,f3,j1,j2,j3");

		jLabel5.setText("操作:");

		jLabel6.setText("花牌:");

		jTextFieldHua.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldHuaActionPerformed(evt);
			}
		});

		jComboBoxHand.setModel(new javax.swing.DefaultComboBoxModel<String>(
				new String[] { "w1", "w2", "w3", "w4", "t1", "t2", "t3", "t4" }));
		jComboBoxHand.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxHandActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jSeparator1))
								.addGroup(layout.createSequentialGroup().addGap(54, 54, 54)
										.addGroup(
												layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout.createSequentialGroup().addComponent(jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(jTextFieldHua))
														.addGroup(
																layout.createSequentialGroup().addComponent(jLabel5)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(jTextFieldOpts))
														.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
																247, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																layout.createSequentialGroup().addComponent(jLabel1)
																		.addGap(18, 18, 18)
																		.addComponent(jTextFieldUri,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				490, Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(jButtonConnect)
																		.addGap(18, 18, 18).addComponent(jButtonLogin)
																		.addGap(20, 20, 20)
																		.addComponent(jButtonClose))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
																.createSequentialGroup().addComponent(jButtonCreate)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jButtonJoin)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jButtonReady)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jComboBoxHand,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jButtonOutCard)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jButtonFetch)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jButtonPeng)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jButtonAnGang)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jButtonMingGang)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jButtonBuGang)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jButtonHu)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(jButtonSend))
														.addComponent(jScrollPane1,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jScrollPane2,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
																229, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(layout.createSequentialGroup().addComponent(jLabel4)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jTextFieldHand,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 1,
																		Short.MAX_VALUE)))
										.addGap(75, 75, 75)))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(jTextFieldUri, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButtonConnect).addComponent(jButtonClose).addComponent(jButtonLogin))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
						.addComponent(jTextFieldHand, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5)
						.addComponent(jTextFieldOpts, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6)
						.addComponent(jTextFieldHua, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18).addComponent(jLabel2)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jButtonCreate).addComponent(jButtonJoin).addComponent(jButtonReady)
						.addComponent(jButtonOutCard).addComponent(jButtonFetch).addComponent(jButtonSend)
						.addComponent(jButtonPeng).addComponent(jButtonAnGang).addComponent(jButtonMingGang)
						.addComponent(jButtonBuGang).addComponent(jButtonHu).addComponent(jComboBoxHand,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel3)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
				.addGap(19, 19, 19)));

		pack();
	}// </editor-fold>

	private void jTextFieldUriActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {
		Session session = CommonSevice.getInstance().connectToServer(this, weixin, this.jTextFieldUri.getText());
		this.jEditorPaneReceive
				.setText(null != session ? "WebSocket Connected" : "WebSocket Connect Error,View Detail Log!");
	}

	private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {
		if (null != CommonSevice.getInstance().getSession()) {
			try {
				CommonSevice.getInstance().getSession().close();
				this.jEditorPaneReceive.setText("WebSocket Closed!");
			} catch (Exception e) {
				// TODO Auto-generated catch block
				this.jEditorPaneReceive.setText("WebSocket Close failed!" + e.getMessage());
			}
		}

	}

	private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {
		weixin.setLocation(this.getLocation().x + this.getWidth() / 2 - weixin.getWidth() / 2,
				this.getLocation().y + this.getHeight() / 2 - weixin.getHeight() / 2);
		weixin.setVisible(true);
	}

	private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {
		CommonSevice.getInstance().sendMsg(this.jEditorPaneSend.getText());
		//this.jEditorPaneReceive.setText(reciveMsg);
	}

	private void jButtonOutCardActionPerformed(java.awt.event.ActionEvent evt) {
		// String hands = this.jTextFieldHand.getText();
		CommonSevice.getInstance().outCard(this.jComboBoxHand.getSelectedItem().toString());
	}

	private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String input = JOptionPane.showInputDialog(this, "请输入房间参数,格式:{1;2,3,4}", "房间参数,格式:{1;2,3,4}",
				JOptionPane.INFORMATION_MESSAGE);
		CommonSevice.getInstance().create(input);
	}

	private void jTextFieldHuaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		CommonSevice.getInstance().buHua(this.jComboBoxHand.getSelectedItem().toString());
	}

	private void jButtonJoinActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// JOptionPane.showInputDialog("输入房间号");
		String input = JOptionPane.showInputDialog(this, "请输入房间号", "加入房间", JOptionPane.INFORMATION_MESSAGE);
		CommonSevice.getInstance().join(input);
		// JOptionPane.showMessageDialog(this, input);
	}

	private void jButtonReadyActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		CommonSevice.getInstance().ready("");
	}

	private void jButtonFetchActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		CommonSevice.getInstance().fetch("");
	}

	private void jButtonPengActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		CommonSevice.getInstance().peng(this.jComboBoxHand.getSelectedItem().toString());
	}

	private void jButtonAnGangActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		CommonSevice.getInstance().anGang(this.jComboBoxHand.getSelectedItem().toString());
	}

	private void jButtonMingGangActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		CommonSevice.getInstance().mingGang(this.jComboBoxHand.getSelectedItem().toString());
	}

	private void jButtonBuGangActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		CommonSevice.getInstance().buGang(this.jComboBoxHand.getSelectedItem().toString());
	}

	private void jButtonHuActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		CommonSevice.getInstance().hu(this.jComboBoxHand.getSelectedItem().toString());
	}

	private String selectCard = null;

	private void jComboBoxHandActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.selectCard = this.jComboBoxHand.getSelectedItem().toString();
		// JOptionPane.showMessageDialog(this, selectCard);
	}


	public String getSelectCard() {
		return selectCard;
	}

	public WeixinJDialog getWeixin() {
		return weixin;
	}

	public JComboBox<String> getjComboBoxHand() {
		return jComboBoxHand;
	}

	public JButton getjButtonAnGang() {
		return jButtonAnGang;
	}

	public JButton getjButtonBuGang() {
		return jButtonBuGang;
	}

	public JButton getjButtonClose() {
		return jButtonClose;
	}

	public JButton getjButtonConnect() {
		return jButtonConnect;
	}

	public JButton getjButtonCreate() {
		return jButtonCreate;
	}

	public JButton getjButtonFetch() {
		return jButtonFetch;
	}

	public JButton getjButtonHu() {
		return jButtonHu;
	}

	public JButton getjButtonJoin() {
		return jButtonJoin;
	}

	public JButton getjButtonLogin() {
		return jButtonLogin;
	}

	public JButton getjButtonMingGang() {
		return jButtonMingGang;
	}

	public JButton getjButtonOutCard() {
		return jButtonOutCard;
	}

	public JButton getjButtonPeng() {
		return jButtonPeng;
	}

	public JButton getjButtonReady() {
		return jButtonReady;
	}

	public JButton getjButtonSend() {
		return jButtonSend;
	}

	public JEditorPane getjEditorPaneReceive() {
		return jEditorPaneReceive;
	}

	public JEditorPane getjEditorPaneSend() {
		return jEditorPaneSend;
	}

	public JLabel getjLabel1() {
		return jLabel1;
	}

	public JLabel getjLabel2() {
		return jLabel2;
	}

	public JLabel getjLabel3() {
		return jLabel3;
	}

	public JLabel getjLabel4() {
		return jLabel4;
	}

	public JLabel getjLabel5() {
		return jLabel5;
	}

	public JLabel getjLabel6() {
		return jLabel6;
	}

	public JScrollPane getjScrollPane1() {
		return jScrollPane1;
	}

	public JScrollPane getjScrollPane2() {
		return jScrollPane2;
	}

	public JSeparator getjSeparator1() {
		return jSeparator1;
	}

	public JTextField getjTextFieldHand() {
		return jTextFieldHand;
	}

	public JTextField getjTextFieldHua() {
		return jTextFieldHua;
	}

	public JTextField getjTextFieldOpts() {
		return jTextFieldOpts;
	}

	public JTextField getjTextFieldUri() {
		return jTextFieldUri;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainJFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButtonAnGang;
	private javax.swing.JButton jButtonBuGang;
	private javax.swing.JButton jButtonClose;
	private javax.swing.JButton jButtonConnect;
	private javax.swing.JButton jButtonCreate;
	private javax.swing.JButton jButtonFetch;
	private javax.swing.JButton jButtonHu;
	private javax.swing.JButton jButtonJoin;
	private javax.swing.JButton jButtonLogin;
	private javax.swing.JButton jButtonMingGang;
	private javax.swing.JButton jButtonOutCard;
	private javax.swing.JButton jButtonPeng;
	private javax.swing.JButton jButtonReady;
	private javax.swing.JButton jButtonSend;
	private javax.swing.JComboBox<String> jComboBoxHand;
	private javax.swing.JEditorPane jEditorPaneReceive;
	private javax.swing.JEditorPane jEditorPaneSend;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextField jTextFieldHand;
	private javax.swing.JTextField jTextFieldHua;
	private javax.swing.JTextField jTextFieldOpts;
	private javax.swing.JTextField jTextFieldUri;
	// End of variables declaration
}
